// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGbxwdJ0hL5uXy5yw2qkkBN-gKOphE3L0',
    appId: '1:464864732965:web:9738752625a2539a58dccc',
    messagingSenderId: '464864732965',
    projectId: 'flutternonstop',
    authDomain: 'flutternonstop.firebaseapp.com',
    storageBucket: 'flutternonstop.appspot.com',
    measurementId: 'G-81LQ2TP6VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbC6IuTVTrk-elLUp6n2ELrbkEZiSNw4o',
    appId: '1:464864732965:android:77a0ce1361cfa76058dccc',
    messagingSenderId: '464864732965',
    projectId: 'flutternonstop',
    storageBucket: 'flutternonstop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTmDpygT_j075F0T9X0wG1tzd4OG9C0V0',
    appId: '1:464864732965:ios:a2552cb2c174a21958dccc',
    messagingSenderId: '464864732965',
    projectId: 'flutternonstop',
    storageBucket: 'flutternonstop.appspot.com',
    iosClientId: '464864732965-lvdnjt490nlhlpc5su3tli9jiut5cen2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstMobexFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTmDpygT_j075F0T9X0wG1tzd4OG9C0V0',
    appId: '1:464864732965:ios:60cea4d09442395758dccc',
    messagingSenderId: '464864732965',
    projectId: 'flutternonstop',
    storageBucket: 'flutternonstop.appspot.com',
    iosClientId: '464864732965-4cam1uvti0m7qml14t7qkc95ak1bd6v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstMobexFlutterProject.RunnerTests',
  );
}
